--DDL

DROP TABLE IF EXISTS YOGESH.Y_CUSTOMER;
/
CREATE TABLE YOGESH.Y_CUSTOMER 
   (	
	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	PHONE NUMBER, 
	TOTAL_DAY_POINT NUMBER, 
	 CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DATA  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE DATA ;
/
GRANT ALTER, SELECT ,UPDATE ,INSERT , DELETE  ON YOGESH.Y_CUSTOMER TO PUBLIC;
/

CREATE SEQUENCE  YOGESH.Y_CUSTOMER_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON YOGESH.Y_CUSTOMER_ID_SEQ TO PUBLIC;
/
--DML
Insert into YOGESH.Y_CUSTOMER (ID,NAME,PHONE,TOTAL_DAY_POINT) values (YOGESH.Y_CUSTOMER_ID_SEQ.nextval,'Yogesh',9594960234,100);
Insert into YOGESH.Y_CUSTOMER (ID,NAME,PHONE,TOTAL_DAY_POINT) values (YOGESH.Y_CUSTOMER_ID_SEQ.nextval,'Pavan',2222222222,20);
Insert into YOGESH.Y_CUSTOMER (ID,NAME,PHONE,TOTAL_DAY_POINT) values (YOGESH.Y_CUSTOMER_ID_SEQ.nextval,'Pratik',1111111111,20);
Insert into YOGESH.Y_CUSTOMER (ID,NAME,PHONE,TOTAL_DAY_POINT) values (YOGESH.Y_CUSTOMER_ID_SEQ.nextval,'Ravi',5555555555,10);
commit;
/